# Generated by Django 4.1.7 on 2023-03-24 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='is_active',
        ),
    ]
